### ISSUE TITLE
Configuring non-regional failover

### ISSUE THREAD

**Issue by mans0954** [terraform-google-modules/terraform-google-sql-db#263]
### TL;DR

Using other means (e.g. Google Cloud Deployment Manager) it's possible to configure failover for the zonal availability type. E.g.
```
gcloud --project **** sql instances describe ******
backendType: SECOND_GEN
...
failoverReplica:
  available: true
  name: ******
...
settings:
  activationPolicy: ALWAYS
  availabilityType: ZONAL
  backupConfiguration:
    backupRetentionSettings:
      retainedBackups: 7
      retentionUnit: COUNT
    binaryLogEnabled: true
    enabled: true
    kind: sql#backupConfiguration
    startTime: 02:00
    transactionLogRetentionDays: 7
```
If it's possible to configure this using `terraform-google-sql-db` then I can't figure it out from the documentation or the code.

### Terraform Resources

See `failover_target` in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance
